L-003 Level Finished All 3 Mini Games and Applied Materials
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-12 pull request #108
Opened 2024-11-30 14:09 UTC by b1lly13

# PR Title [Descriptive title summarizing the change]
## Related Issue(s)
L-003-1 
## PR Description
There are 3 mini games in the stage that have been completed, each level has different methods to complete the stage. After you complete each mini game,  player can move to the "straight" path at the end of the level.
### Changes Included
- [o] 3 Mini Games
- [o] Materials
- [o] Fixed lever position to account for rigidbody

### Screenshots (if UI changes were made)
<img width="582" alt="image" src="https://github.com/user-attachments/assets/d067259e-dc87-4bef-905b-3980d6d6ba41">

### Notes for Reviewer
Any specific instructions or points to be considered by the reviewer.
---
## Reviewer Checklist
- [ ] All mini games do not have any unexpected bugs
- [ ] If any paths that does not work as expected
- [ ] Level difficulty is appropriate

---
## Additional Comments
Add any other comments or information that might be useful for the review process.
linter.yml:

2024-11-30 16:34 UTC, parkchaehyun reviewed
<img width="212" alt="스크린샷 2024-12-01 오전 1 32 08" src="https://github.com/user-attachments/assets/2e557eec-9452-4f2b-807d-4dd6b4d88818">

여기서 동그라미 친 레버가 이미 레이저를 막아줘서 레버를 누를 필요가 없는 느낌이네요.. 그렇다고 레버가 없으면 막을 수가 없고요.. 원래 의도는 레버를 안 누르면 죽고 레버를 눌러야 막을 수 있는 건가요?

2024-11-30 16:38 UTC, parkchaehyun reviewed
https://github.com/user-attachments/assets/672d790c-8333-4808-b61f-1204fb805a94

이건 레벨 설계의 문제는 아니고 코드를 나중에 고쳐야할 부분인데, 일단 기록을 위해 여기 남겨둡니다.

영상처럼 이동하는 경우 사는 것이 아니라 죽도록 변경해야합니다.

2024-11-30 17:02 UTC, parkchaehyun reviewed
<img width="335" alt="스크린샷 2024-12-01 오전 2 01 35" src="https://github.com/user-attachments/assets/8d286057-8087-4f25-9cf4-74ae3cc425e9">
저 버튼이 저 레이저를 키면 안 되지 않나요? 저게 켜져 있으면 중앙으로 못 돌아가는 것 같은데요

2024-11-30 17:08 UTC, parkchaehyun reviewed
![image](https://github.com/user-attachments/assets/e260e896-2a34-4db2-991f-51009e86cbfe)

여기에 들어오면 나갈 수가 없네요.. ㅋㅋ 저기 동그라미 친 칸을 타일로 채워서 잘못 들어왔을 때 나갈 수 있게 하면 어떨까요?

2024-11-30 17:18 UTC, parkchaehyun reviewed
https://github.com/user-attachments/assets/748fbd1a-2c29-4570-8888-c3d64d108d7a

18초에 레버를 누르면 플레이어가 멈추고 어느 키를 눌러도 움직이지 않네요.. 성환님은 잘 되시나요?

2024-11-30 17:19 UTC, parkchaehyun requested changes
리뷰했습니다. 한번 확인해주세요~

2024-11-30 19:53 UTC, b1lly13 commented
L-003 PR 코멘트 확인 (처음부터 순서대로)

- 네 원래 의도는 레버를 안 누르면 죽고 레버를 눌러야 막을 수 있는 거였습니다
- 스킵
- 토끼 점프 모션 때문에 타일이 낮아져도 죽네요.. 하 계속 고민을 해봤는데 옵젝끼리 활성시킬 수가 없으니까 방법이 없네요 (레버/버튼이 다른 레버/버튼을 활성) 그냥 열어놓을까요?
- 저기에 고립되면 Undo 키 사용하면 되지 않을까요
- 18초에는 낙하 구현이 안되어 있어서 타일이 사라질 때 떨어지진 않는게 맞는데, 애초에 채현님꺼에서는 분신이 사라지질 않아서 타일이 안 사라지네요..? 제꺼에선 타일 잘 사라집니다

2024-11-30 20:11 UTC, parkchaehyun commented
1. 같은 위치에서 플레이어의 왼쪽 (현재)이 아닌 플레이어의 뒤쪽에 레버를 두면 어떨까요?

2024-11-30 21:17 UTC, b1lly13 commented
1.  넵 그렇게 반영해서 커밋했습니다 (쉬운 버젼과 어려운 버젼 중에 어려운걸로 했습니다)
5. 어라 그것도 제꺼에선 괜찮았던 것 같은데.. 근데 3번 고치면서 수정했습니다 이제 아마 괜찮을 거에요
추가: 처음 레이저 object 제거
Uploading 1번 풀이영상.mov…

2024-11-30 21:18 UTC, b1lly13 commented
1. 넵 그렇게 반영해서 커밋했습니다 (쉬운 버젼과 어려운 버젼 중에 어려운걸로 했습니다)
5. 어라 그것도 제꺼에선 괜찮았던 것 같은데.. 근데 3번 고치면서 수정했습니다 이제 아마 괜찮을 거에요
추가: 처음 레이저 object 제거
https://github.com/user-attachments/assets/73bff110-2da9-4ff6-b47f-9cc1f1bbd677

2024-12-01 06:06 UTC, parkchaehyun approved these changes
위에 말씀드렸던 다 해결된 것 같네요. 수고하셨습니다~

2024-12-01 06:33 UTC, merged