[F-039] 튜토리얼 레벨 조작키 설명 추가
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-12 pull request #144
Opened 2024-12-14 02:56 UTC by ahchowww

# [F-039] 튜토리얼 레벨 조작키 설명 추가
## Related Issue(s)

## PR Description
- WASD+R key usage and time rewind key explanations that disappear after three inputs
- Add explanation for box and lever mechanics: instruction will occur only if the player is within a 3x3 radius of the object
### Changes Included
- [x] Added new feature(s)
- [ ] Fixed identified bug(s)
- [ ] Updated relevant documentation
### Screenshots (if UI changes were made)

### Notes for Reviewer
---
## Reviewer Checklist
- [ ] Code is written in clean, maintainable, and idiomatic form.
- [ ] Automated test coverage is adequate.
- [ ] All existing tests pass.
- [ ] Manual testing has been performed to ensure the PR works as expected.
- [ ] Code review comments have been addressed or clarified.
---
## Additional Comments

linter.yml:

2024-12-14 07:56 UTC, parkchaehyun reviewed
우선 develop에 rebase했습니다

2024-12-14 08:01 UTC, parkchaehyun requested changes

2024-12-14 08:01 UTC, parkchaehyun commented on Chronus/Assets/Scripts/TutorialManager.cs
> +    public Transform box;
어차피 같은 transform type이니 public Transform object 정도로 하나만 사용해서 tile, lever, box 모두 사용하면 될 것 같습니다

setlever, setbox, clearlever, clearbox도 set clear 하나씩으로 합치구요

2024-12-15 16:20 UTC, ahchowww commented on Chronus/Assets/Scripts/TutorialManager.cs
> +    public Transform box;
반영했습니다.

![Screenshot 2024-12-16 004311](https://github.com/user-attachments/assets/5fb7878b-2649-448b-8502-c56b1fd84756)

GameInstructionCanvas와 TimeRewindInstructionCanvas에도 동일한 방법을 적용했습니다. StartTile 근처에 있는 타일에 'TutorialTile' 태그를 추가했습니다

2024-12-16 05:45 UTC, parkchaehyun approved these changes
변경해주신 것 확인했습니다. 고생하셨습니다.

2024-12-16 06:04 UTC, merged