F 004 -> Develop
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-12 pull request #62
Opened 2024-11-08 10:16 UTC by GyubinKimProg

F-004(Turn system, Player's Log save/edit) <-merge-> Develop(Animator, rabbit model)

2024-11-08 16:43 UTC, parkchaehyun requested changes
전체적으로 잘 해주신 것 같습니다! 수고하셨습니다

PlayerHop이랑 PlayerMove 코드가 겹치는게 좀 걸리는데, Design Pattern 공부를 더 해보고 여기에 적용해보면 좋을 것 같네요

2024-11-09 04:56 UTC, GyubinKimProg commented on Chronus/Assets/Scripts/TurnManager.cs
> +    */
실제로 저게 원래 public enum이었는데 
singleton으로 접근가능하게 만들어놨는데도 저게 안 불러와져서
그냥 포기하고 string으로 바꿨습니다
그냥 저건 예전 잔재입니다..

2024-11-09 04:56 UTC, GyubinKimProg commented on Chronus/Assets/Scripts/PlayerHop.cs
>              targetTranslation = _playerController.playerCurPos + new Vector3(0, 1.0f * _playerController.curHopDir, -2.0f); //Ȥ�ó��� ���� ���ɼ� ������ ��Ȯ�� ��ġ �Է�����
한글이 아직 남아있더라구요 저건 commit하면서 바로 수정해둘게요

2024-11-09 04:57 UTC, GyubinKimProg commented on Chronus/Assets/Scripts/PlayerTurn.cs
> +        /*
넵

2024-11-09 04:59 UTC, GyubinKimProg commented on Chronus/Assets/Scripts/PlayerController.cs
> +                }
다음 commit때 리팩토링해두겠습니다

2024-11-09 05:53 UTC, GyubinKimProg commented on Chronus/Assets/Scripts/PlayerTurn.cs
> +        /*
아 그런데 이 부분은 floating point라서 저렇게 나눗셈 관련 연산 하면 계속 오차가 생길 것 같아서
현재처럼 더하기 빼기로만 표현하는 게 맞을 것 같습니다
가독성도 좋고요

2024-11-09 05:56 UTC, GyubinKimProg commented
리팩토링 완료했습니다!

2024-11-09 06:59 UTC, parkchaehyun approved these changes
훨씬 깔끔해진 것 같네요. 수고하셨습니다~

2024-11-09 06:59 UTC, merged